### ISSUE TITLE
Lost "console-toggle"

### ISSUE THREAD

**Issue by sglyon** [JunoLab/atom-julia-client#107]
With all the changes in the past few weeks I think we lost the ability to _close_ the console panel.

Before `ctrl-`` would toggle the console, so it would open (close) the console if it was closed (open).

I liked being able to close it, can we get that back?

**Comment by ViralBShah** [comment]
Tangential, but worth mentioning - I was just telling @one-more-minute that the default Juno distribution should have the dark theme.

**Comment by one-more-minute** [comment]
Yup, going dark is the right move and I believe it's already change in our atom fork, so that should be out with the next bundle build.

There were a couple of reasons that the toggle console command wasn't working for me, number one being that ``ctrl-` `` didn't work reliably on windows, but also it seemed easier to just combine `cmd-j cmd-o` to open with `cmd-w` to close. That's also nice as it means the former doubles as a `focus console` command – and more flexibility with fewer commands seems like a good goal for us to have in general.

If it's still seems useful I'd be happy to expose the toggle-console command in some way so that you can still set up a keybinding for it.

**Comment by ChrisRackauckas** [comment]
`` ctrl-` `` always worked great for me on Windows (Windows 10). Could this at least have an option for us to choose the key command? I'm still sad it's gone months later!

**Comment by pfitzseb** [comment]
Well, you could always add 
```cson
'.platform-win32 atom-workspace, .platform-linux atom-workspace':
  'ctrl-`': 'julia-client:open-console'
```
to your `keymap.cson` which would at least bind those keys to opening the console.
I kinda liked a console toggle command too, by the way, but the biggest problem I have with the current console implementation is that we don't remember the pane size (different issue though).
