### ISSUE TITLE
PCRE.exec error: match limit exceeded

### ISSUE THREAD

**Issue by CarloLucibello** [JunoLab/atom-julia-client#112]
I'm constantly having this error in Atom on atom-julia-client master and julia 0.4. I'm on Linux. Bye

**Comment by one-more-minute** [comment]
Is there a stacktrace, or any other information, that comes with the error?

**Comment by CarloLucibello** [comment]
I cannot reproduce the bug anymore, I'm closing this for the time being

**Comment by MikeInnes** [comment]
Thanks – although I recently saw this myself so it does appear to be an issue. I'll keep an eye out for a reproducible case.

**Comment by KristofferC** [comment]
I also got this when I was editing some long function definition but could have just been something else.

**Comment by Varanas** [comment]
This seems related to the length of function names:
```julia
abcdefghijklmnopqrstu(a)
```
doesn't show the error, while
```julia
abcdefghijklmnopqrstuv(a)
```
does when trying to get autocomletions for `a`.

Indeed, there's a bug in CodeTools with [this regexp](https://github.com/JunoLab/CodeTools.jl/blob/63e0f3fad620d97f07d85dfd4b9d491923b5091a/src/completions.jl#L71):
```julia
CodeTools.prefix("abcdefghijklmnopqrstuv(as)")
```
gives 
```
PCRE.exec error: match limit exceeded
 in error at error.jl:21
```

Changing that regexp to
```julia
const prefix_pattern = r"(@?[_\p{L}][_\p{L}\p{N}!]*+\.?)+$|@$"
```
(note the additional `+` to make the `*` a possessive instead of a greedy quantifier) makes the regexp work even for very long function names. 

I've gone ahead and made that change [here](https://github.com/JunoLab/CodeTools.jl/commit/834d8040316fef7af61312c4d9b6495891ae6d6e). Hopefully doesn't break anything...

**Comment by MikeInnes** [comment]
Awesome, glad to see this figured out, and it seems to work nicely!

**Comment by zsoerenm** [comment]
+1
