### ISSUE TITLE
LoadError: Failed to precompile Atom

### ISSUE THREAD

**Issue by Dani-ela** [JunoLab/atom-julia-client#131]
Hi everyone,

I installed Atom according to https://github.com/JunoLab/atom-julia-client/tree/master/manual.
But the "Julia Client: Toggle Console" command doesn't appear and when I try to run a julia-file I get the following error messages in the console:

INFO: Precompiling module Atom...
ERROR: LoadError: LoadError: UndefVarError: get_obj_meta not defined
 in hasdoc at C:\Users\Daniela\.julia\v0.4\CodeTools\src\summaries.jl:24
 in fullsignature at C:\Users\Daniela\.julia\v0.4\CodeTools\src\summaries.jl:29
 in withmeta at C:\Users\Daniela\.julia\v0.4\CodeTools\src\completions.jl:49
 [inlined code] from C:\Users\Daniela\.julia\v0.4\CodeTools\src\completions.jl:55
 in anonymous at no file:0
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:284
 in _start at client.jl:411
while loading C:\Users\Daniela\.julia\v0.4\CodeTools\src\completions.jl, in expression starting on line 54
while loading C:\Users\Daniela\.julia\v0.4\CodeTools\src\CodeTools.jl, in expression starting on line 14
ERROR: LoadError: LoadError: Failed to precompile CodeTools to C:\Users\Daniela\.julia\lib\v0.4\CodeTools.ji
 in error at error.jl:21
while loading C:\Users\Daniela\.julia\v0.4\Atom\src\eval.jl, in expression starting on line 1
while loading C:\Users\Daniela\.julia\v0.4\Atom\src\Atom.jl, in expression starting on line 9
ERROR: LoadError: Failed to precompile Atom to C:\Users\Daniela\.julia\lib\v0.4\Atom.ji
 in error at error.jl:21
while loading C:\Users\Daniela\.atom\packages\julia-client\script\boot.jl, in expression starting on line 19

Can anyone help me with that problem?

**Comment by pfitzseb** [comment]
Hi,

`Julia Client: Toggle Console` is now `Julia Client: Open Console` (or `Ctrl-J Ctrl-O`), if you're on the latest version of julia-client, so that might explain why you couldn't find it.

Can you try `Pkg.update()` in a Julia REPL, followed by `using Atom`? Does this fail as well? If so, the output of `Pkg.status()` and `versioninfo()` might be interesting.

**Comment by MichaelHatherly** [comment]
CodeTools is using `Docs.get_obj_meta` which was backported in Julia 0.4.1, but not present in 0.4.0, which looks to be the problem here. It's always been unexported and has now been removed in 0.5, so would be best to use a different approach for [`hasdoc`](https://github.com/JunoLab/CodeTools.jl/blob/834d8040316fef7af61312c4d9b6495891ae6d6e/src/summaries.jl#L24-L26). Something like

```julia
function hasdoc(b::Binding)
    obj = b[]
    for m in Docs.modules
        meta = Docs.meta(m)
        if haskey(meta, b) || haskey(meta, obj)
            return true
        end
    end
    true
end
```

should be stable across all versions, I think. Might be worth while exporting a `hasdoc` from `Base`, since I've also needed to do this check myself.

**Comment by pfitzseb** [comment]
Yeah, that implementation looks good (except for the `true` in the last line) -- adding this to Base would be great. In the meantime (until it's backported, should that happen) we should probably use that implementation in `CodeTools` as well, no?

**Comment by Dani-ela** [comment]
Yeah, I'm using 0.4.0 and that fixed the problem.
Thanks a lot!

**Comment by blairn** [comment]
So, what do we do for now? 0.4.6  does not have get_obj_meta, So Juno doesn't doesn't work.

**Comment by pfitzseb** [comment]
`Pkg.checkout("CodeTools")` should work for now, I think.

**Comment by blairn** [comment]
it does, thank you!
