### ISSUE TITLE
Toggle documentation from within function parentheses

### ISSUE THREAD

**Issue by prcastro** [JunoLab/atom-julia-client#138]
Can't toggle the documentation for `print()` it if my cursor is within the parentheses.

**Comment by pfitzseb** [comment]
So I was thinking about this the other day, and imho this isn't really worth it since the logic for determining which docs to get would get pretty complicated and you could just move the cursor to the side. 

If someone wants to implement this feature, feel free to do so, but I don't think I will ;)
