### ISSUE TITLE
Add startup-arguments option

### ISSUE THREAD

**Issue by isaiasmanuel** [JunoLab/atom-julia-client#140]
Hi!
I'm trying make parallel programing, when i'm in the Shell i add -p 2, before the binary julia's path, but when i'm in Juno or in Atom i don't know how do that. Can you help me?

**Comment by Mike43110** [comment]
You could go `addprocs(2)` in your script.
You should also probably do something like: `addprocs(x+1-length(procs()))` to make sure that you only have `x` number of processes extra

**Comment by isaiasmanuel** [comment]
Thanks

**Comment by pfitzseb** [comment]
Should we have a setting for custom julia start-up options?

**Comment by Mike43110** [comment]
Can't you just add a line in settings for command line options? Then just append the Julia link with them?
It will be useful I think if you suddenly want to run -O like I normally do (2 hour run times = no caring for compile times) or want to test with no inlining etc.

**Comment by MikeInnes** [comment]
In theory that's fine, in practice there are weird OS differences to worry about. It might be more user-friendly, and easier to implement, to have settings like optimisation level directly available in the julia-client settings. For stuff like processes you can also stick a line in `~/.juliarc.jl` (and we could have a `~/.junorc.jl` file as well if that's useful.

**Comment by ChrisRackauckas** [comment]
While I don't think this is necessary for `-p` since you can just `addprocs()`, this does come up when you're using multiple nodes and setting up the parallel computation via a `--machinefile`. Also, it would be nice for optimizations like `--check-bounds` and `--math-mode`. So while not the original issue, the spirit of adding the command line arguments seems very useful to me.

**Comment by pfitzseb** [comment]
Implemented on master.
