### ISSUE TITLE
Option for Disable Plot Capturing

### ISSUE THREAD

**Issue by ChrisRackauckas** [JunoLab/atom-julia-client#179]
Sometimes in certain setups the plot capturing doesn't work properly. Also, sometimes having the plots being captured is not optimal. For example, with multiple monitor setups I would like to keep my plots on another monitor, and currently I do not see a way of doing that with Atom. Having an option to disable plot capturing is a quick fix to these issues.

**Comment by MikeInnes** [comment]
So I mentioned some of this on Gitter, just to expand and for the record:

[Media.jl](https://github.com/JunoLab/Media.jl) handles linking data types to displays in Juno. By default, `Media.Graphical` types are linked to the `Atom.PlotPane()` display, but you can change that:

```julia
Media.setdisplay(Media.Graphical, Atom.BlinkDisplay._display)
```

That will make plots show up in a new window (at least so long as they support the Media API – gadfly does). You can also unset display so that it falls through to Base's display system:

```julia
Media.unsetdisplay(Media.Graphical)
```

This is useful if packages rely on overloading `display` or `show` for custom display, although it's not a great long-term strategy.

In general the foundations for this stuff are pretty solid, but we do need to polish up the APIs and finalise things, particularly so that package authors can easily extend this to their own types.

**Comment by francoisdlouw** [comment]
I'm using PlotlyJS, but using either 
`Media.setdisplay(Media.Graphical, Atom.BlinkDisplay._display)`

or 

`Media.unsetdisplay(Media.Graphical)`

doesn't work for me.

**Comment by francoisdlouw** [comment]
Some more info: I'm using Atom 1.14.2 x64 and Julia 0.5.0.

Previously using Julia 0.4.7 and some earlier version of Atom I never actually had the plots showing up in the plot pane and was quite happy with that. Since Atom upgraded itself and forced me to update everything else including Julia I am not actually able to use plots like I did before, where I was using PlotlyJS via the Plots.jl interface.

**Comment by ChrisRackauckas** [comment]
If you use the command `gui()` it should still open the plot window.

**Comment by francoisdlouw** [comment]
If I use the following:
```
import Plots

Plots.plotlyjs()

x = collect(0:0.1:2*pi);
y = sin(x);

Plots.plot(x,y)
```

Then it plot correctly in the Atom Plot Pane, although with the following warning:
`show(IO, Base.Multimedia.MIME{:text/plain}, Plots.Plot{#B<:Any}) in module Plots at C:\Users\flouw\.julia\v0.5\Plots\src\output.jl:196 overwritten in module Main at C:\Users\flouw\.julia\v0.5\Plots\src\output.jl:289.`

If I then issue the following 

```
Media.setdisplay(Media.Graphical, Atom.BlinkDisplay._display)
Plots.plot(x,y)
```

The window pops up but no plot is displayed, and I get the following on the console:

```
WARNING: 
Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
WARNING: 
Base.writemime is deprecated.
  likely near C:\Users\flouw\.atom\packages\julia-client\script\boot.jl:327
in tohtml at C:\Users\flouw\.julia\v0.5\Atom\src\blink\mimes.jl
```

If I issue a `Plots.gui()` after that then it ends up in the Atom Plot Pane again.
