### ISSUE TITLE
syntax: unexpected end error

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-julia-client#198]
I'm getting the following error trying to evaluate some Julia code in the editor window (i.e. not the console). Here's as simple as I can get it while still reproducing the error. 

``` julia
module foo
function bar()
    [x for x=1:2]
end
end 

> syntax: unexpected end
 in include_string at /home/marius/.julia/v0.4/CodeTools/src/eval.jl:28
 in include_string at /home/marius/.julia/v0.4/CodeTools/src/eval.jl:32
 [inlined code] from /home/marius/.julia/v0.4/Atom/src/eval.jl:39
 in anonymous at /home/marius/.julia/v0.4/Atom/src/eval.jl:62
```

I'm on atom-julia-client 0.4.7, atom 1.7.3, Julia 0.4.5.

**Comment by MikeInnes** [comment]
Where is the cursor when you try to evaluate? My guess is that this is happening because you're at the final `end`, and as Juno's block finding is indent-sensitive it only picks up on that keyword. You can verify this with `C-Shift-A` (the "select block" command).

You can indent the function if you want the whole module to count as a block. It's possible that we could be smarter in this case, but I'm also wary of making block-finding more complex – the priority should be that it is easily predictable.

**Comment by marius311** [comment]
This happens no matter where I place the cursor. Indeed indenting it does get rid of the error, but in any case indenting functions inside a module is against the Julia style guide. 

But I think its must just be a bug because, its related to the list comprehension, i.e. this works just fine:

```julia
module foo
function bar()
    x = 4 #or any other non-list comprehension lines
end
end 
```

Maybe the parses is picking up the `for` inside the comprehension and thinking its a for loop and not finding it's `end`?

**Comment by MikeInnes** [comment]
Ah I see now – thanks a lot for the extra detail. I guess this is because we're treating the `for` as the start of a for loop and therefore absorbing the extra `end` erroneously. Should be straightforward to fix that.

**Comment by marius311** [comment]
Thanks, yea, I should have mentioned the importance of the list comprehension!
