### ISSUE TITLE
please do completion on tab

### ISSUE THREAD

**Issue by JeffBezanson** [JunoLab/atom-julia-client#204]
I find the way completion currently works extremely annoying, constantly popping up boxes while I type. I would much prefer to get the very nice completions box on `tab` only. Maybe this could be configurable.

**Comment by MikeInnes** [comment]
Autocompletion has more options than you can shake a stick at, just head into the `autocomplete-plus` settings from the main settings menu. This is the top one.

**Comment by JeffBezanson** [comment]
Ok, thanks. I clearly don't know how to use this thing.

**Comment by MikeInnes** [comment]
No worries, it's not always super obvious what features/settings are coming from where. These issues are good suggestions for future docs :)

**Comment by JeffBezanson** [comment]
I unchecked that option and put the following in `~/.atom/keymap.cson`:

```
'atom-text-editor':
  'tab': 'autocomplete-plus:activate'
```

However it still doesn't seem to work. I can still get completion with ctrl-space, but not with tab.

**Comment by pfitzseb** [comment]
Try
```
'atom-text-editor:not([mini])':
  'tab': 'autocomplete-plus:activate
```

The selector needs to be at least as specific as the one you want to override, which is 
```
'atom-text-editor:not([mini])':
  'tab': 'editor:indent'
```
in this case.

**Comment by JeffBezanson** [comment]
That worked, thanks!

I also notice completion sometimes seems to take a very long time --- julia is at 100% cpu for many seconds. Is that due to fuzzy matching? Is there a way to disable fuzzy matching for julia completions?

**Comment by pfitzseb** [comment]
No, the fuzzy matching happens in Atom. 
I've only seen signifcant delays when getting the first completion in a session, because we get all completions (plus minimal docstrings) then; there may also be some compilation overhead, not sure. I guess if you're getting completions for some module with a lot of functions that might take some time as well, but not multiple seconds.

Disabling fuzzy matching is possible in prinicple, but that'd need to be implemented -- right now we're relying on the built in matching.
