### ISSUE TITLE
@time produces strange output

### ISSUE THREAD

**Issue by MLackner** [JunoLab/atom-julia-client#393]
If enter `@time 1+1` in the console or running it from a file it produces the following output (i.e. I get strange linebreaks in the console):

```

@time 1+1

 
 
 0.
00000
7 seconds
 (
5
 allocations
: 
208 
bytes
)
2
```

**Comment by MLackner** [comment]
Problem is gone.

**Comment by zygmuntszpak** [comment]
I have the same problem using Ink 0.7.9, julia-client 0.6.6. and Atom 1.18.

**Comment by pfitzseb** [comment]
Yeah, the current heuristic for inserting cell breaks is pretty basic. Just for the record, are you two by any chance using Windows? 
@zygmuntszpak Your Atom version is pretty outdated -- while updating probably won't help with this specifc issues it's a good idea nonetheless.

I'll tag this as "wontfix" since we're in the process of transitioning to a completly new text-only console.

**Comment by MLackner** [comment]
> Yeah, the current heuristic for inserting cell breaks is pretty basic. Just for the record, are you two by any chance using Windows?

Jepp. Using Windows.
