### ISSUE TITLE
Toggling console on and off has wacky behavior

### ISSUE THREAD

**Issue by spencerlyon2** [JunoLab/atom-julia-client#43]
Check this out:

![toggle_console_wacky](https://cloud.githubusercontent.com/assets/1001948/10080224/6e5bf378-62bc-11e5-9ffa-bd759915db6b.gif)

All I'm doing there is `ctrl-BACKTICK` many times. Notice that it swaps which pane the console is attached to (see the active cursor show up at the end of the highlighted line on the left pane every other time the console disappears). I think this is a problem with which becomes active when console pane is destroyed. I haven't dug into it yet to see if that is our problem or Atom's

**Comment by Varanas** [comment]
I think this is our problem -- since all three elements (the two editors and the console) are panes and therefore created equal Atom apparently just picks one of them. 

It should be enough to explicitly set the original focused pane [here](https://github.com/JunoLab/atom-ink/blob/master/lib/console/console.coffee#L96). This could be done by setting some kind of parent pane for the console or something.

Another solution would be to not automatically focus the console after toggling it on. This should make the console appear below the selected pane even when repeatedly toggling it.

**Comment by one-more-minute** [comment]
Right now we integrate completely with Atom's mechanisms for opening views and such and the issue still appears, so it seems like it must be an upstream issue.

**Comment by spencerlyon2** [comment]
Also, we don't have a toggle console command anymore, so this issue is kinda moot
