### ISSUE TITLE
Atom not defined when clearing the workspace in the REPL

### ISSUE THREAD

**Issue by CBongiova** [JunoLab/atom-julia-client#450]
Hello, 

I have just re-installed the new version of the atom-julia client. 
I have noticed that when I clear the workspace, the REPL prints out the following message: 
<img width="773" alt="screen shot 2018-04-03 at 10 46 07" src="https://user-images.githubusercontent.com/24223801/38239255-807dbcde-372c-11e8-87e3-3087a308d9c5.png">
Any idea on what is going on and how to fix this? For the moment I have just being restarting Julia every time this error message appears...

Thanks!

**Comment by pfitzseb** [comment]
Don't use `workspace` is the fix, basically :-)
You should generally not need to do that since you can re-eval everything in Juno. Restarting Julia also shouldn't be very time consuming if you use the process cycler (which is enabled by default).
Lastly, Julia 0.7 won't have `workspace` anyways, so best get used to that now ;-)

**Comment by CBongiova** [comment]
Thanks! :D

**Comment by pfitzseb** [comment]
We now have [limited support for this](https://github.com/JunoLab/Atom.jl/commit/24a710c3ede32b48abde8939e5ba26e5f71fefbe), but I still wouldn't recommend using `workspace()` since it will definitely break the debugger for example. Basic functionality should still work since that commit though.
