### ISSUE TITLE
How to cycle through terminals with Ctrl+PgUp/PgDown ? 

### ISSUE THREAD

**Issue by marius311** [JunoLab/atom-julia-client#458]
I'd like to have `Ctrl+PgUp/PgDown` invoke `pane:show-next/previous-item` even when inside a Terminal/REPL so that I can use this to cycle through Terminals/REPLs in the same way it works for open files or in the native Linux terminal. However, I think julia-client intercepts these keystrokes since the Key Binding Resolver never sees them if I press them inside a Terminal/REPL. Is there a way to make this work? Thanks.

**Comment by pfitzseb** [comment]
Yeah, this is a bit annyoing and I'm not entirely sure on how to solve it. 
Basically, the terminal intercepts most keybindings -- we can register custom handlers to keep certain keybindings from being intercepted (like `Ctrl-C` in the REPL), but doing this generically is hard because we can't know which keybindings should be passed through to Atom.

**Comment by marius311** [comment]
I guess `Ctrl+PgUp/PgDown` would be a pretty safe one to add to the "dont intercept" list since that's almost ubiquitously next/prev tab in most terminals? (or at least, Gnome and XFCE terminals that I've just tried). More generally yea its unclear how best to handle this.

**Comment by saschatimme** [comment]
I also got recently a little bit frustrated that the default keybinding for switching windows and panes get intercepted. Maybe we could add the default bindings for these? They are
* `cmd-k cmd-left` window:focus-pane-on-left
* `cmd-k cmd-right` window:focus-pane-on-right
* `cmd-k cmd-up` window:focus-pane-above
* `cmd-k cmd-down` window:focus-pane-below
* `alt-cmd-left` pane:show-previous-item
* `alt-cmd-right` pane:show-next-item

**Comment by pfitzseb** [comment]
Well, for MacOS it's a bit easier since all of those shortcuts use <kbd>Cmd</kbd> which isn't usually used for terminal commands afaik. On Windows and Linux they use `Ctrl-K` etc, which are much more likely to be used by whatever terminal app you're running.

The latest release kind of has a short term solution -- you can use `Ctrl-J Ctrl-E` to focus the last used editor (`Ctrl-J Ctrl-O` for the REPL, and `Ctrl-J Ctrl-T` for the last used terminal).

Long term I'd like to look at the keybindings for that exact css selector and pass those to Atom instead of the terminal. This would allow users to customize those keybindings just like any other, but also means we don't inherit all keybindings from parent elements -- you'd have to add those pane keybindings yourself.

**Comment by pfitzseb** [comment]
Latest master has an option for whitelisting keybindings which are then not handled by the terminal but instead directly passed to Atom's keybinding resolver.

**Comment by Oblynx** [comment]
Although the whitelisted keybindings work for single keybindings like `Ctrl-w`, they don't work for sequences like `Ctrl-w right`.

I tried adding both `Ctrl-w` and `Ctrl-w right` to the REPL whitelist. The result is that `Ctrl-w` is interpreted by Atom as intended, but the sequence isn't.
