### ISSUE TITLE
@__FILE__ macro returns empty string when evaluated

### ISSUE THREAD

**Issue by stillyslalom** [JunoLab/atom-julia-client#46]
I poked around the Julia internals a bit in an attempt to fix it myself, but I don't understand the problem well enough to make headway. `current_task().storage` returns a dict that has the following contents: 

```julia
ObjectIdDict(
:bindings=>Dict{Any,Any}(Lazy.Binding{Any}(nothing)=>Atom.Editor()),
:SHOWNSET=>ObjectIdDict(#= circular reference =#=>true,#= circular reference =#=>true))
```

The `@__FILE__` macro requires that the dict returns a value for `:SOURCE_PATH`, but I can't figure out where the dict is constructed or how the value for `SOURCE_PATH` would be determined.

**Comment by MichaelHatherly** [comment]
`@__FILE__` requires that the current file is a saved file rather than just an `untitled` editor window. It appears to be working for me:

![2015-09-27-1443335793_crop](https://cloud.githubusercontent.com/assets/6144086/10121573/285cecd6-64f3-11e5-89fb-abc2991c11c7.png)

What versions of the packages are you using? You may need to update since I think this was fixed with https://github.com/JunoLab/Atom.jl/commit/649ce2cf0d5e212ea8161d5ea1892855eb1efeca.

**Comment by stillyslalom** [comment]
Sure enough, checking out the latest version fixed the issue. Thanks!
