### ISSUE TITLE
can't install julia-client0.9.4

### ISSUE THREAD

**Issue by searchengineorientprogramming** [JunoLab/atom-julia-client#594]
I have download and install julia and atom, but when I try to install juno in atom(uber-juno 0.2.0), error shows up: Installing “julia-client@0.9.4” failed. Then I install julia-client@0.9.4 alone, it failed and I attach debug.log below:

[2019-08-20T04_30_14_829Z-debug.log](https://github.com/JunoLab/atom-julia-client/files/3518715/2019-08-20T04_30_14_829Z-debug.log)

Can anyone help me? Thanks!!!

**Comment by searchengineorientprogramming** [comment]
My atom verison is 1.40, running on win10

**Comment by hellsy** [comment]
i had the same issue here.I am using Mac OS 10.14.6.Work on permanentely for the last two days but no success seeing at the moment.

**Comment by pfitzseb** [comment]
This is a bug with Atom 1.40 (will be fixed in 1.40.1). For now you'll have to downgrade to Atom 1.39.

See [here](https://discourse.julialang.org/t/juno-fails-to-install-julia-client-0-9-4/27544?u=pfitzseb) for updates. Also dup of https://github.com/JunoLab/atom-julia-client/issues/590#issuecomment-522774368, so I'm closing this.

**Comment by searchengineorientprogramming** [comment]
It worked! thank you!
