### ISSUE TITLE
DOC: document how setting the current working module works

### ISSUE THREAD

**Issue by spencerlyon2** [JunoLab/atom-julia-client#6]
Sorry to post this here: I know this isn't ready for public consumption yet.  My justification is that if I understand this, I can start using, and then I can start contributing :)

Anyway, I want to understand what setting the current working module does. Suppose I'm working on a package `Lazy.jl`. My current editor+terminal based workflow is to do something like this:

```
include(Pkg.dir("Lazy", "src", "Lazy.jl"))

the_number_2 = Lazy.cycle([1, 2, 3])[50]

# ... more code that always prefixes access to things in Lazy with `Lazy.`

# then make a change to something in the Lazy source
# so now I overwrite the module by doing another...
include(Pkg.dir("Lazy", "src", "Lazy.jl"))

# and now I can prefix with `Lazy.` and get the updated code from the new module definition
```

(I'm sure this is not the optimal way to do this, so tips for improving the workflow would be appreciated!)

I'm _hoping_  that setting the current working module will allow me to not need to refresh the module with my `include(Pkg.dir(...)` hack. Is that true? If so, how does it work and how do we do things like refresh the module after a change?

**Comment by one-more-minute** [comment]
>  My justification is that if I understand this, I can start using, and then I can start contributing :)

That sounds like a pretty great justification to me ;) I'm glad you asked. You're workflow looks pretty standard to me, although I'm hoping to ween people of it and onto something a bit more efficient. In future perhaps we can put together some video tutorials or something more visual to get the idea across, but for now I'll just outline some thoughts.

The module indicator tells you what module Julia is going to evaluate into (so long as it's not greyed out), so if you evalute while it says Lazy (for example), you'll have unqualified access to everything defined in Lazy.jl, even if it's not exported. Try `current_module()` if you're not sure. Likewise, if you go into Lazy and evalute `f(x) = 2x`, you'll find that from the repl or console you can do `Lazy.f(1)` and it works. You can even eval `export f` from within Lazy and `f` will become available in Main unqualified (assuming you've already done `using Lazy`).

If you want to change the definition of `f`, just tweak the definition at will and re-evaluate. That's it; no need to do `include` hacks, reboot everything, or qualify, it's just updated in place. This is particularly nice when working on Base, or a large package, since you can modify things and try them out without having to wait several minutes to completely compile Julia.

Needing to outright replace modules is relatively rare, but might be necessary if you want to redefine a type or constant. In that case just open the file containing `module Lazy ...` and `Ctrl-Shift-Enter`, which is roughly equivalent to `include`ing it. This will bring up the qualifying issue again if you're working from the repl, but it's not so much of a big deal since you can carry on evaluating into files set to work in `Lazy`. It's often useful to open a blank buffer as a scratch pad -- set the syntax to Julia, then click the module indicator and choose `Lazy` to work directly in the Lazy module.

Does that roughly make sense? It might be useful just to play around with it; I think it's pretty intuitive once you get used to it, just not that obvious. Once you get to the point where you rarely have to reboot/load files, it's a really nice productivity boost.

**Comment by spencerlyon2** [comment]
This is an excellent description! 

What you are describing here is exactly what I was hoping you were going to describe ;) When I get back to developing more code I'll certainly play around more with it and give you some feedback if I have any.

Thanks

**Comment by spencerlyon2** [comment]
This might be closable with the workflow docs

What do you think?

**Comment by one-more-minute** [comment]
Yup, I think this has been fixed nicely ;)
