### ISSUE TITLE
Start Julia / Stop Julia fails sometimes in the newer versions

### ISSUE THREAD

**Issue by aminya** [JunoLab/atom-julia-client#696]
In the recent versions of Julia Client, the `Restart Julia Client` command fails in Juno-Plus. I am not sure if this is related to Julia-Client, but I didn't have this issue before, so I want to know if anything has changed regarding `Start Julia`, `Stop Julia` commands.

https://github.com/aminya/juno-plus/issues/8

![image](https://user-images.githubusercontent.com/16418197/75475844-1f4b1180-595f-11ea-8cfb-712f7ca6dab5.png)

**Comment by kczimm** [comment]
I'm having the same issue. If I want to restart the REPL, I have to restart Atom. Very frustrating.

**Comment by pfitzseb** [comment]
We're looking into this, but it's fairly hard to figure out what's going on since the crash doesn't show a stacktrace (or an error, for that matter).

**Comment by rezabayani** [comment]
This. The exact same happens to me. I am using the latest Atom, Juno and Julia. I used to face this issue occasionally (which in itself was frustrating) but in the past few days (after the update I guess) this got worse and I have to manually close and open Atom to restart REPL

**Comment by aminya** [comment]
> 
> 
> @pfitzseb
> This. The exact same happens to me. I am using the latest Atom, Juno and Julia. I used to face this issue occasionally (which in itself was frustrating) but in the past few days (after the update I guess) this got worse and I have to manually close and open Atom to restart REPL. I get the error "Can't interrupt Julia without a Julia client running. Start a client with Packages -> Juno -> Start Julia." and when I try to start nothing happens. The minibar at the bottom left gets stuck on "working" mode too

For now, you can use `Ctrl+P` + `Reload` to reload Atom without openning and closing.

**Comment by rezabayani** [comment]
@aminya Thanks for the tip but it doesn't work for me. Ctrl + P opens a window with some random files from my pwd I guess. Also, is there any other way to clear workspace besides stop and restart?

**Comment by aminya** [comment]
> 
> 
> @aminya Thanks for the tip but it doesn't work for me. Ctrl + P opens a window with some random files from my pwd I guess.

Sorry `Ctrl+Shift+P` that opens the command window. 

>  Also, is there any other way to clear workspace besides stop and restart?

For development, you can use Revise.jl. There is a Revise button in Juno-Plus: https://github.com/aminya/juno-plus

**Comment by aviatesk** [comment]
Well, for this juno-plus case, the code that needs to be modified is not in julia-client, but in juno-plus.
I remember I told @aminya  how to "implement" `Restart Julia` command, but now the `atom.dispatch` command doesn't return a `Promise` anymore and that just causes this error.

You can see my current implementation [here](https://github.com/aviatesk/avi-atom/blob/master/init.js#L148-L158) and this should work for your package as well (it's really ad-hoc, though).

***

Separate from that, there is certainly issues of crashes on killing->restarting Julia process within the latest releases. But I would like to open an separate issue for that at Juno.jl, since this issue is originally for the one within juno-plus.

**Comment by aviatesk** [comment]
Let me close this in favor of https://github.com/JunoLab/Juno.jl/issues/510.
