### ISSUE TITLE
Some Problem

### ISSUE THREAD

**Issue by scottchanhosing** [JunoLab/atom-julia-client#89]
It shows "Atom not found in path" when i run Julia code.

**Comment by ssfrr** [comment]
what do you see when you run `which julia` from your terminal? (this will confirm that Julia is installed correctly and on your system PATH).

If julia seems to be installed, make note of where it says it's finding it, then in Atom open the developer console and run `process.env["PATH"]` to see what paths Atom will look in.

You have a few options for getting Atom to find Julia:
1. explicitly set the path to Julia in the julia-client package settings
2. make sure that julia is installed to the PATH that atom is seeing
3. start Atom from the console so that it picks up your shell's PATH

**Comment by scottchanhosing** [comment]
problem solved. thz so much!

**Comment by Sinooshka** [comment]
Sorry for the basic question !
you mentioned : 
"explicitly set the path to Julia in the julia-client package settings"

I can not do that. could you please elaborate more how it take places with the latest version of atom 1.6.2 
I installed everything according to this link : 
https://github.com/JunoLab/atom-julia-client/tree/master/manual

But I can not connect Atom and Julia together !

**Comment by MikeInnes** [comment]
Go to the Packages->Julia->Settings menu and you'll see the config option in there. If you're not sure what path to fill in there are some instructions in the manual, otherwise we'll need a more detailed idea of what you're trying to do – and what's not working – in order to help.

**Comment by Sinooshka** [comment]
Works 
I was not able to find this Setting menu !
Thanks a lot indeed

**Comment by MikeInnes** [comment]
No problem, enjoy Juno!
